import DiffractionScatteringCanonicalLaneLean.AdmissibleClass

namespace HautevilleHouse
namespace DiffractionScatteringCanonicalLaneLean

end DiffractionScatteringCanonicalLaneLean
end HautevilleHouse